name: Deploy demo
on:
  push:
    branches:
      - main
jobs:
  deploy-server:
    name: Deploy server
    runs-on: ubuntu-latest
    concurrency: deploy-server-group
    steps:
      - uses: actions/checkout@v6
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-demo:
    name: Deploy web demo
    runs-on: ubuntu-latest
    concurrency: deploy-demo-group
    steps:
      - uses: actions/checkout@v6
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config demo/fly.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
