name: Deploy demo
on:
  push:
    branches:
      - main
  paths:
    - "demo/**"

jobs:
  deploy:
    name: Deploy web demo
    runs-on: ubuntu-latest
    concurrency: deploy-web-group
    steps:
      - uses: actions/checkout@v6
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config demo/fly.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
